#!/usr/bin/env bash
SCRIPT_DIR="$(cd -P -- "$(dirname -- "$0")" && pwd -P)"
. $SCRIPT_DIR/.addonenv.sh

EXECUTABLE="`basename $0`"

if [ "$HELP" == "true" ]; then
   echo "SYNOPSIS"
   echo "   ./$EXECUTABLE [-?]"
   echo ""
   echo "DESCRIPTION"
   echo "   Deletes the orders table Kafka sink connector"
   echo ""
   echo "DEFAULT"
   echo "   ./$EXECUTABLE"
   echo ""
   exit
fi

CONNECT_URL=http://localhost:8083/connectors
curl -X DELETE $CONNECT_URL/orders-sink
