#!/usr/bin/env bash
SCRIPT_DIR="$(cd -P -- "$(dirname -- "$0")" && pwd -P)"
. $SCRIPT_DIR/.addonenv.sh

EXECUTABLE="`basename $0`"

if [ "$HELP" == "true" ]; then
   echo "SYNOPSIS"
   echo "   ./$EXECUTABLE [-?]"
   echo ""
   echo "DESCRIPTION"
   echo "   Initializes the MySQL database."
   echo ""
   echo "DEFAULT"
   echo "   ./$EXECUTABLE"
   echo ""
   exit
fi

# Create nw database and grant all permissions to the user debezium
docker exec -e MYSQL_PWD=debezium -it ${CLUSTER_NAME}-mysql-1 /bin/bash -c \
"mysql -uroot -e \"GRANT ALL PRIVILEGES ON nw.* TO 'debezium'@'%'; CREATE DATABASE IF NOT EXISTS nw;\""
echo "nw database created."


