#!/usr/bin/env bash
SCRIPT_DIR="$(cd -P -- "$(dirname -- "$0")" && pwd -P)"
. $SCRIPT_DIR/.addonenv.sh

EXECUTABLE="`basename $0`"

if [ "$HELP" == "true" ]; then
   echo "SYNOPSIS"
   echo "   ./$EXECUTABLE [-?]"
   echo ""
   echo "DESCRIPTION"
   echo "   Registers the customers table Kafka sink connector"
   echo ""
   echo "DEFAULT"
   echo "   ./$EXECUTABLE"
   echo ""
   exit
fi

curl -X POST -H "Content-Type: application/json" -d @connector-data-customers.json http://localhost:8083/connectors
