#!/usr/bin/env bash
SCRIPT_DIR="$(cd -P -- "$(dirname -- "$0")" && pwd -P)"
. $SCRIPT_DIR/.addonenv.sh

EXECUTABLE="`basename $0`"

if [ "$HELP" == "true" ]; then
cat <<EOF
SYNOPSIS
   ./$EXECUTABLE [-?]

DESCRIPTION
   Starts the MSQL client

DEFAULT
   ./$EXECUTABLE
EOF
   exit
fi

docker exec -e MYSQL_PWD=debezium -it ${CLUSTER_NAME}_mysql_1 /bin/bash -c "mysql -uroot"
