#!/usr/bin/env bash
SCRIPT_DIR="$(cd -P -- "$(dirname -- "$0")" && pwd -P)"
. $SCRIPT_DIR/.addonenv.sh

EXECUTABLE="`basename $0`"

if [ "$HELP" == "true" ]; then
cat <<EOF
SYNOPSIS
   ./$EXECUTABLE [-?]

DESCRIPTION"
   Displays the Kafka log

DEFAULT
   ./$EXECUTABLE
EOF
   exit
fi

docker-compose exec connect /bin/bash -c "tail -f /kafka/logs/connect-service.log"

